"""empty message

Revision ID: 2b128b758880
Revises: 66aab768c8e9
Create Date: 2022-03-19 18:48:32.217329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b128b758880'
down_revision = '66aab768c8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_poll_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'poll', ['poll_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('poll_category_id_fkey', 'poll', type_='foreignkey')
    op.drop_constraint('poll_user_id_fkey', 'poll', type_='foreignkey')
    op.create_foreign_key(None, 'poll', 'category', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'poll', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('user_auth0_id_key', 'user', type_='unique')
    op.drop_column('user', 'auth0_id')
    op.drop_constraint('vote_user_id_fkey', 'vote', type_='foreignkey')
    op.drop_constraint('vote_answer_id_fkey', 'vote', type_='foreignkey')
    op.drop_constraint('vote_poll_id_fkey', 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'vote', 'poll', ['poll_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'vote', 'answer', ['answer_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'vote', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'vote', schema='public', type_='foreignkey')
    op.create_foreign_key('vote_poll_id_fkey', 'vote', 'poll', ['poll_id'], ['id'])
    op.create_foreign_key('vote_answer_id_fkey', 'vote', 'answer', ['answer_id'], ['id'])
    op.create_foreign_key('vote_user_id_fkey', 'vote', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('auth0_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_auth0_id_key', 'user', ['auth0_id'])
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'poll', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'poll', schema='public', type_='foreignkey')
    op.create_foreign_key('poll_user_id_fkey', 'poll', 'user', ['user_id'], ['id'])
    op.create_foreign_key('poll_category_id_fkey', 'poll', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'answer', schema='public', type_='foreignkey')
    op.create_foreign_key('answer_poll_id_fkey', 'answer', 'poll', ['poll_id'], ['id'])
    # ### end Alembic commands ###
