"""empty message

Revision ID: ea6195fbbe60
Revises: 3aca628d8b80
Create Date: 2022-03-18 20:04:13.516403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6195fbbe60'
down_revision = '3aca628d8b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('center', sa.String(), nullable=True),
    sa.Column('restriction', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('visibility', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['public.category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['public.poll.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['public.answer.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['public.poll.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'poll_id'),
    schema='public'
    )
    op.add_column('user', sa.Column('auth0_id', sa.String(), nullable=False))
    op.add_column('user', sa.Column('longtitude', sa.Numeric(), nullable=True))
    op.add_column('user', sa.Column('latitude', sa.Numeric(), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user', sa.Column('ethnicity', sa.String(), nullable=True))
    op.add_column('user', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('user', sa.Column('religion', sa.String(), nullable=True))
    op.add_column('user', sa.Column('income_range', sa.String(), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(), nullable=True))
    op.add_column('user', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('user', sa.Column('veteran', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['auth0_id'], schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='public', type_='unique')
    op.drop_column('user', 'veteran')
    op.drop_column('user', 'marital_status')
    op.drop_column('user', 'education')
    op.drop_column('user', 'income_range')
    op.drop_column('user', 'religion')
    op.drop_column('user', 'industry')
    op.drop_column('user', 'ethnicity')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'age')
    op.drop_column('user', 'latitude')
    op.drop_column('user', 'longtitude')
    op.drop_column('user', 'auth0_id')
    op.drop_table('vote', schema='public')
    op.drop_table('answer', schema='public')
    op.drop_table('poll', schema='public')
    op.drop_table('category', schema='public')
    # ### end Alembic commands ###
